// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/kernal/kernal.proto

package kernal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TracePoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracePoint) Reset()         { *m = TracePoint{} }
func (m *TracePoint) String() string { return proto.CompactTextString(m) }
func (*TracePoint) ProtoMessage()    {}
func (*TracePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_6daece36524d26ee, []int{0}
}

func (m *TracePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracePoint.Unmarshal(m, b)
}
func (m *TracePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracePoint.Marshal(b, m, deterministic)
}
func (m *TracePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracePoint.Merge(m, src)
}
func (m *TracePoint) XXX_Size() int {
	return xxx_messageInfo_TracePoint.Size(m)
}
func (m *TracePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_TracePoint.DiscardUnknown(m)
}

var xxx_messageInfo_TracePoint proto.InternalMessageInfo

func (m *TracePoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TracePoint)(nil), "kernal.trace_point")
}

func init() { proto.RegisterFile("src/kernal/kernal.proto", fileDescriptor_6daece36524d26ee) }

var fileDescriptor_6daece36524d26ee = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2e, 0x4a, 0xd6,
	0xcf, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x81, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c,
	0x10, 0x9e, 0x92, 0x22, 0x17, 0x77, 0x49, 0x51, 0x62, 0x72, 0x6a, 0x7c, 0x41, 0x7e, 0x66, 0x5e,
	0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x98, 0x9d, 0xc4, 0x06, 0xd6, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x49, 0x14, 0x98, 0x58,
	0x4c, 0x00, 0x00, 0x00,
}
